---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel
  namespace: redis
  labels:
    environment: prod
    tier: cache
    app.kubernetes.io/name: sentinel
    app.kubernetes.io/instance: sentinel
    app.kubernetes.io/version: "7.2"
    app.kubernetes.io/component: sentinel
