---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: php-app
  namespace: php-app
  labels:
    environment: prod
    tier: frontend
    app.kubernetes.io/name: php-app
    app.kubernetes.io/instance: php-app
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      environment: prod
      tier: frontend
      app.kubernetes.io/name: php-app
      app.kubernetes.io/instance: php-app
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/component: frontend
