---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-admin
  namespace: redis
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: redis-admin-password
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: redis/prod/admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-app
  namespace: redis
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: redis-app-password
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: redis/prod/php-app
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-replication
  namespace: redis
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: redis-replication-password
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: redis/prod/replication
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: redis-sentinel-password
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: redis/prod/sentinel
        property: password
